name: DRONE-RENDER

on:
  workflow_dispatch:
    inputs:
      affiliate_link:
        description: 'Link Affiliate'
        required: true
      image1:
        description: 'Hình ảnh 1'
        required: true
      image2:
        description: 'Hình ảnh 2'
        required: true
      image3:
        description: 'Hình ảnh 3'
        required: true
      image4:
        description: 'Hình ảnh 4'
        required: true

jobs:
  update-landing-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Renderer
        run: |
          python render-image.py \
            --affiliate_link "${{ github.event.inputs.affiliate_link }}" \
            --image1 "${{ github.event.inputs.image1 }}" \
            --image2 "${{ github.event.inputs.image2 }}" \
            --image3 "${{ github.event.inputs.image3 }}" \
            --image4 "${{ github.event.inputs.image4 }}"
